# Generated by Django 2.1 on 2019-06-29 02:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('secciones', '0006_auto_20190628_2304'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=60)),
                ('Apellido', models.CharField(max_length=60)),
                ('email', models.EmailField(max_length=254)),
                ('Direccion', models.CharField(max_length=150)),
                ('Codigo_Postal', models.CharField(max_length=30)),
                ('Ciudad', models.CharField(max_length=100)),
                ('Creado', models.DateTimeField(auto_now_add=True)),
                ('Actualizado', models.DateTimeField(auto_now=True)),
                ('Pago', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('-Creado',),
            },
        ),
        migrations.CreateModel(
            name='OrdenItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orden.Orden')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orden_items', to='secciones.Producto')),
            ],
        ),
    ]
