# Generated by Django 2.1.3 on 2018-11-13 01:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('secciones', '0002_compra'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotadePedido',
            fields=[
                ('id_notadepedido', models.AutoField(primary_key=True, serialize=False)),
                ('Fecha', models.DateField()),
                ('Hora', models.TimeField()),
                ('Estado', models.CharField(max_length=20)),
                ('Usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
