# Generated by Django 2.1.3 on 2018-11-13 03:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('secciones', '0003_notadepedido'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorito',
            fields=[
                ('id_favorito', models.AutoField(primary_key=True, serialize=False)),
                ('Usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProductoFavorito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Favorito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='secciones.Favorito')),
                ('Producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='secciones.Producto')),
            ],
        ),
    ]
