# Generated by Django 2.1.7 on 2019-03-14 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secciones', '0004_favorito_productofavorito'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'ordering': ('Nombre',), 'verbose_name': 'categoria', 'verbose_name_plural': 'categorias'},
        ),
        migrations.AlterModelOptions(
            name='producto',
            options={'ordering': ('Modelo',), 'verbose_name': 'Producto', 'verbose_name_plural': 'Productos'},
        ),
        migrations.AddField(
            model_name='categoria',
            name='Slug',
            field=models.SlugField(default=str, editable=False, max_length=150, unique=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='disponibilidad',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, upload_to='products/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='producto',
            name='slug',
            field=models.SlugField(default=str, max_length=150),
        ),
    ]
