# Generated by Django 2.1 on 2019-06-29 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secciones', '0005_auto_20190314_1941'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'ordering': ('Nombre',), 'verbose_name': 'Categoria', 'verbose_name_plural': 'Categorias'},
        ),
        migrations.AlterModelOptions(
            name='localidad',
            options={'ordering': ('Nombre',), 'verbose_name': 'Localidad', 'verbose_name_plural': 'Localidades'},
        ),
        migrations.AlterModelOptions(
            name='proveedor',
            options={'ordering': ('Razon_social',), 'verbose_name': 'Proveedor', 'verbose_name_plural': 'Proveedores'},
        ),
        migrations.AlterField(
            model_name='categoria',
            name='Slug',
            field=models.SlugField(default=str, max_length=150, unique=True),
        ),
    ]
